name: xeus-kernels
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  # - dash
  # - werkzeug>=2.2,<3.0
  - httpx
  - numpy
  - pandas
  # - tornado
  # - blinker>=1.5.0,<2
  # - cachetools>=4.0,<7
  # - protobuf
  # - altair
  # - pyarrow
  # - starlette
  # - htmltools
  # - panel
  # - textual
  # - textual-serve
  # - vizro
  - fastapi
  - pillow
  - huggingface_hub
  - aiofiles
  - safehttpx
  - semantic_version
  - pydub
  - tomlkit
  - pip:
    # - shiny
    # - shinychat
    # - vega_datasets
    # - streamlit==1.50.0
    - gradio
    - pyodide_http
    - gradio-client
    - ../dist/jupyterpack-0.0.0-py3-none-any.whl

